# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' || true
      - git fetch --all --tags || true
    pre_install:
      - git update-index --assume-unchanged docs/conf.py
    post_install:
      - git describe --exact-match || towncrier build --keep

python:
  install:
    - method: uv
      command: pip
      requirements: requirements-docs.txt

# Don't build any extra formats
formats: []
