name: build

on:
  release:
    types: [released]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@e5af21e4ae37af089a73bb032e10b78b0e746174 # v3.0.1
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
