name: build

on:
  release:
    types: [released]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@4193751d511425d4edc1d5657c24b2128d49b017 # v2.6.4
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
