name: test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/nox_matrix.yml
    with:
      kind: test
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  rtd-python:
    name: check Read the Docs Python version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
      - run: uv tool run --with requests nox -s rtd-python
